In [1]:
#2.1
import numpy as np
print(np.__version__)
np.show_config()


1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Libr

In [2]:
#2.2
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#2.3
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
#2.4
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [6]:
#2.5
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#2.6
Z = np.random.random(30)
m = Z.mean()
print(Z)
print(m)

[0.52702043 0.05370549 0.22665869 0.35777521 0.10792883 0.58165942
 0.05378409 0.46766969 0.49150721 0.38080189 0.61979393 0.6429231
 0.87080905 0.91591214 0.59170454 0.87020299 0.30242789 0.35447854
 0.5782688  0.33965242 0.55676475 0.77171167 0.23224352 0.72219264
 0.71905555 0.4880988  0.2564711  0.24262676 0.75228601 0.70068678]
0.49256073067535816


In [8]:
#2.7
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
#2.8
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#2.9
x=np.ones((3,3), dtype=bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
#3.1
import numpy as np
my_array = np.array([1, 2, 3, 4])
my_slice = my_array[1:3]
print(my_slice)

[2 3]


In [12]:
#3.2
my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

In [13]:
#3.3
import numpy as np
my_array = np.array( [1, 2, 3] )
my_slice = my_array[1:3]
my_slice = my_slice * 2
print(my_slice)

[4 6]


In [14]:
#3.4
import numpy as np
my_array = np.array( [[1, 2, 3], [4, 5, 6]])
my_slice = my_array[:, 1:3]
print(my_slice)

[[2 3]
 [5 6]]


In [15]:
#3.5
import numpy as np
first_matrix = np.array( [ [1, 2, 3], [4, 5, 6] ] )
second_matrix = np.array([1, 2, 3])
my_matrix=first_matrix + second_matrix
print(my_matrix)

[[2 4 6]
 [5 7 9]]


In [16]:
#3.6
import numpy as np
X = np.array( [ [ [ 1, 2,3], [ 4, 5, 6]],
[ [7,8,9], [10,11,12] ] ] )
print(X.shape)
print(X.ndim)
print(X.size)

(2, 2, 3)
3
12


In [18]:
#5
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr_even = arr[1::2]
print(arr_even)

[ 2  4  6  8 10]


In [22]:
#6
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
a = arr1==arr2
print(a)
b = arr1>arr2
print(b)
c = arr1<arr2
print(c)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
