In [2]:
#2
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [3]:
#3
import numpy as np
a = np.array([1, 0, -1, -4])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(a>=0)

Original array
[ 1  0 -1 -4]
Test element-wise for positive or negative infinity:
[ True  True False False]


In [4]:
#4
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
#5
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
#6
import numpy as np
array=np.random.randint(100 , size=(3,3))
print("An array of 3 X 3 zeros:")
print(array)
print("An array of divisible by 3 and 5:")
filter= (array%3==0) & (array%5==0 )
print( array[ filter])

An array of 3 X 3 zeros:
[[56  0 43]
 [29  2 33]
 [ 5  0  7]]
An array of divisible by 3 and 5:
[0 0]


In [7]:
#7
import numpy as np
array=np.random.randint(100 , size=(3,3))
print("An array of 3 X 3 zeros:")
print(array)
print("An array of divisible by 3 and 5:")
filter= (array%2==0)
array[ filter]=0
print(array)

An array of 3 X 3 zeros:
[[26  8 40]
 [34 49 63]
 [62 96 84]]
An array of divisible by 3 and 5:
[[ 0  0  0]
 [ 0 49 63]
 [ 0  0  0]]


In [8]:
#8
x = np.random.randint(100, size=5)
print(x)
x1 = np.random.rand(5)
print(x1)
x2= np.random.choice([3, 5, 7, 9], size=5)
print(x2)

[11 60 90 76 90]
[0.06073634 0.0631316  0.85723803 0.98690537 0.01025718]
[9 9 3 7 9]


In [13]:
#9
A=np.random.randint(100 , size=(3,3))
print("Array A is \n",A)
B=np.random.randint(100 , size=(3,3))
print("Array B is \n",B)
print("The sum of two matrix is \n",np.add(A,B))
print("The product of the two matrix is \n",np.dot(A,B))

Array A is 
 [[59 58  1]
 [64 19 16]
 [17 64  7]]
Array B is 
 [[16 23  7]
 [81 24 36]
 [ 8 50 42]]
The sum of two matrix is 
 [[ 75  81   8]
 [145  43  52]
 [ 25 114  49]]
The product of the two matrix is 
 [[5650 2799 2543]
 [2691 2728 1804]
 [5512 2277 2717]]


In [14]:
#10
A=np.random.randint(100 , size=(3,3))
print("Array A is \n",A)
print("Array A after transpose is \n",np.transpose(A))

Array A is 
 [[84 40 28]
 [63 80  2]
 [86 95 56]]
Array A after transpose is 
 [[84 63 86]
 [40 80 95]
 [28  2 56]]
